USE [master]
GO

/****** Object:  Database [DBofSMTH]    Script Date: 14.10.2020 14:10:43 ******/
CREATE DATABASE [DBofSMTH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBofSMTH', FILENAME = N'D:\SQLserver\MSSQL15.MSSQLSERVER\MSSQL\DATA\DBofSMTH.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBofSMTH_log', FILENAME = N'D:\SQLserver\MSSQL15.MSSQLSERVER\MSSQL\DATA\DBofSMTH_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBofSMTH].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBofSMTH] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBofSMTH] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBofSMTH] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBofSMTH] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBofSMTH] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBofSMTH] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBofSMTH] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBofSMTH] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBofSMTH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBofSMTH] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBofSMTH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBofSMTH] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBofSMTH] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBofSMTH] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBofSMTH] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBofSMTH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBofSMTH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBofSMTH] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBofSMTH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBofSMTH] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBofSMTH] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBofSMTH] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBofSMTH] SET RECOVERY FULL 
GO

ALTER DATABASE [DBofSMTH] SET  MULTI_USER 
GO

ALTER DATABASE [DBofSMTH] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBofSMTH] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBofSMTH] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBofSMTH] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBofSMTH] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBofSMTH] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBofSMTH] SET  READ_WRITE 
GO

